name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - dev # Trigger on pull requests targeting the dev branch
  workflow_dispatch: # Allow manual triggers

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Cache dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn clean package

      # Step 5: Test the application
      - name: Run unit tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy the application (Example: Deploy using Heroku or Docker)
      - name: Deploy to Production
        run: |
          echo "Your deployment commands go here"
